---
version: "3"

services:

  nginx:
    image: nginx:1.22.1
    container_name: program-nginx
    ports:
    - 8181:80
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./hello_world.js:/etc/nginx/hello_world.js