---
version: "3"

services:

  nginx:
    image: nginx:1.22.1
    container_name: program-nginx
    ports:
    - 8181:80
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./sitev1/:/var/www/sitev1/
    - ./passwd:/etc/nginx/conf.d/passwd
